from __future__ import annotations

import logging
import secrets
import uuid
from datetime import datetime, timedelta

import httpx
from google.auth.transport.requests import Request as GoogleRequest
from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import Flow
from googleapiclient.errors import HttpError
from sqlalchemy.orm import Session

from app.core.config import get_settings
from app.core.security import encrypt_str
from app.db import models
from app.services import gmail_data

_log = logging.getLogger(__name__)

_GOOGLE_TOKEN_URI = "https://oauth2.googleapis.com/token"


def _normalize_oauth_credentials(flow: Flow) -> Credentials:
    """Flow.credentials often omit scopes; Gmail / userinfo need explicit scopes + client fields."""
    s = get_settings()
    c = flow.credentials
    return Credentials(
        token=c.token,
        refresh_token=c.refresh_token,
        id_token=c.id_token,
        token_uri=c.token_uri or _GOOGLE_TOKEN_URI,
        client_id=s.google_client_id,
        client_secret=s.google_client_secret,
        scopes=s.scope_list,
        expiry=c.expiry,
    )


def _client_config() -> dict:
    s = get_settings()
    return {
        "web": {
            "client_id": s.google_client_id,
            "client_secret": s.google_client_secret,
            "auth_uri": "https://accounts.google.com/o/oauth2/auth",
            "token_uri": "https://oauth2.googleapis.com/token",
            "redirect_uris": [s.google_redirect_uri],
        }
    }


def _build_flow(redirect_uri: str | None = None) -> Flow:
    s = get_settings()
    if not s.google_client_id or not s.google_client_secret:
        raise RuntimeError("Set GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET in .env")
    # PKCE verifier lives on the Flow instance. We build a new Flow on callback,
    # so autogenerated PKCE breaks token exchange. Web clients with a client
    # secret can use the classic auth-code flow without PKCE.
    return Flow.from_client_config(
        _client_config(),
        scopes=s.scope_list,
        redirect_uri=redirect_uri or s.google_redirect_uri,
        autogenerate_code_verifier=False,
    )


def create_oauth_state(db: Session) -> str:
    state = secrets.token_urlsafe(32)
    row = models.OAuthState(
        id=state,
        expires_at=datetime.utcnow() + timedelta(minutes=15),
    )
    db.add(row)
    db.commit()
    return state


def validate_oauth_state(db: Session, state: str) -> None:
    row = db.get(models.OAuthState, state)
    if not row or row.expires_at < datetime.utcnow():
        raise ValueError("Invalid or expired OAuth state (CSRF)")
    db.delete(row)
    db.commit()


def get_authorization_url_with_state(state: str) -> str:
    flow = _build_flow()
    url, _ = flow.authorization_url(
        access_type="offline",
        include_granted_scopes="true",
        prompt="consent",
        state=state,
    )
    return url


def exchange_code_and_upsert_user(
    db: Session,
    *,
    code: str,
    state: str,
) -> models.User:
    s = get_settings()
    validate_oauth_state(db, state)
    flow = _build_flow()
    # Must match the redirect the browser used
    flow.fetch_token(
        code=code,
    )
    creds = _normalize_oauth_credentials(flow)
    if not creds.refresh_token:
        _log.warning("No refresh token returned — use prompt=consent and try again")
    # Userinfo needs openid/userinfo.* scopes; we only request Gmail scopes, so
    # oauth2/v2/userinfo often returns nothing — use Gmail profile instead.
    uinfo = _userinfo(creds)
    email = (uinfo or {}).get("email")
    if not email:
        try:
            svc = gmail_data.get_gmail_service(creds)
            prof = gmail_data.get_user_profile(svc)
            email = prof.get("emailAddress")
        except HttpError as e:
            _log.warning(
                "Gmail getProfile failed: status=%s body=%s",
                getattr(e.resp, "status", "?"),
                e.content,
            )
        except Exception as e:  # noqa: BLE001
            _log.warning("Gmail getProfile for email failed: %s", e)
    if not email:
        email = "unknown@local"
    name = (uinfo or {}).get("name")
    user = db.query(models.User).filter_by(email=email).first()
    if not user:
        user = models.User(id=str(uuid.uuid4()), email=email, display_name=name)
        db.add(user)
        db.flush()
    else:
        user.display_name = name or user.display_name
    if creds.refresh_token:
        ref_enc = encrypt_str(creds.refresh_token)
    else:
        ref_enc = encrypt_str("")
    acc = creds.token
    acc_enc = encrypt_str(acc) if acc else None
    gt = user.tokens
    if gt is None:
        gt = models.GmailToken(
            user_id=user.id,
            enc_refresh_token=ref_enc,
            enc_access_token=acc_enc,
            access_expires_at=creds.expiry,
            token_scopes=" ".join(creds.scopes or s.scope_list),
        )
        db.add(gt)
    else:
        gt.enc_refresh_token = ref_enc
        if acc_enc:
            gt.enc_access_token = acc_enc
        gt.access_expires_at = creds.expiry
        gt.token_scopes = " ".join(creds.scopes or s.scope_list)
    db.add(models.AuditLog(id=str(uuid.uuid4()), user_id=user.id, event="auth.google.connected", details=None))
    db.commit()
    db.refresh(user)
    return user


def _userinfo(creds: Credentials) -> dict:
    headers = {"Authorization": f"Bearer {creds.token}"}
    with httpx.Client() as client:
        r = client.get(
            "https://www.googleapis.com/oauth2/v2/userinfo",
            headers=headers,
            timeout=20.0,
        )
        if r.status_code == 200:
            return r.json()
        r2 = client.get(
            "https://openidconnect.googleapis.com/v1/userinfo",
            headers=headers,
            timeout=20.0,
        )
        if r2.status_code == 200:
            return r2.json()
    return {}


def credentials_for_user(db: Session, user_id: str) -> Credentials:
    user = db.get(models.User, user_id)
    if not user or not user.tokens or not user.tokens.enc_refresh_token:
        raise ValueError("User has no Google tokens. Complete OAuth2 first.")
    s = get_settings()
    from app.core.security import decrypt_str

    try:
        refresh = decrypt_str(user.tokens.enc_refresh_token) if user.tokens.enc_refresh_token else None
    except Exception:
        raise ValueError("Cannot decrypt stored tokens. Check MASTER_ENCRYPTION_KEY")
    if not refresh:
        raise ValueError("Missing refresh token. Reconnect Google (prompt=consent)")

    access = None
    if user.tokens.enc_access_token:
        try:
            access = decrypt_str(user.tokens.enc_access_token)
        except Exception:
            pass
    creds = Credentials(
        token=access,
        refresh_token=refresh,
        id_token=None,
        token_uri="https://oauth2.googleapis.com/token",
        client_id=s.google_client_id,
        client_secret=s.google_client_secret,
        scopes=s.scope_list,
    )
    if not creds.valid and creds.refresh_token:
        creds.refresh(GoogleRequest())
        user.tokens.enc_access_token = encrypt_str(creds.token) if creds.token else None
        user.tokens.access_expires_at = creds.expiry
        db.add(user)
        db.commit()
    if not creds.token:
        raise ValueError("Could not obtain a valid access token. Re-authenticate")
    return creds


def revoke_and_clear_local(db: Session, user_id: str) -> None:
    from app.core.security import decrypt_str

    u = db.get(models.User, user_id)
    if u and u.tokens:
        for enc in (u.tokens.enc_access_token, u.tokens.enc_refresh_token):
            if not enc:
                continue
            try:
                tok = decrypt_str(enc)
            except Exception:
                continue
            if not tok:
                continue
            try:
                with httpx.Client() as c:
                    c.post(
                        "https://oauth2.googleapis.com/revoke",
                        data={"token": tok},
                        headers={"Content-Type": "application/x-www-form-urlencoded"},
                        timeout=20.0,
                    )
            except Exception:
                pass
            break
    if u and u.tokens:
        db.delete(u.tokens)
    db.add(
        models.AuditLog(
            id=str(uuid.uuid4()), user_id=user_id, event="auth.revoke", details={"ok": True}
        )
    )
    db.commit()

